# -*- coding: utf-8 -*-
# Created by Takuya Ono
# see: https://hub.docker.com/r/nodered/node-red-docker/

services:

  node-red:
    #  <node-red-version>-<node-version>-<image-type>
    #image: nodered/node-red:1.3.2-10-minimal
    image: nodered/node-red$VERSION
    restart: always
    environment:
    #- PORT=1880
    # See: https://github.com/node-red/node-red-docker#startup
    #- NODE_RED_ENABLE_SAFE_MODE=true
    - NODE_RED_ENABLE_PROJECTS=true
    #- FLOWS=flows.json
    #- NODE_OPTIONS=--max-old-space-size=1456
    - NODE_OPTIONS=${NODE_OPTIONS}
    #
    - TZ="Asia/Tokyo"
#    - GOOGLE_APPLICATION_CREDENTIALS=/data/adc.json
    #Secret Variables
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    user: $CUID:$CGID
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./data:/data
#    ports:
#    - "1880:1880"
    networks:
      default:
        ipv4_address: $IP_ADDRESS
    hostname: node-red

  node-red01:
    image: nodered/node-red$VERSION
    restart: unless-stopped
    environment:
    - NODE_RED_ENABLE_PROJECTS=true
    - NODE_OPTIONS=${NODE_OPTIONS}
    - TZ="Asia/Tokyo"
    #Secret Variables
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    user: $CUID:$CGID
    volumes:
    - ./data01:/data
    networks:
      default:
        ipv4_address: $IP_ADDRESS01
    hostname: node-red01

  node-red02:
    image: nodered/node-red:2.1.4
    restart: unless-stopped
    environment:
    - NODE_RED_ENABLE_PROJECTS=true
    - NODE_OPTIONS=${NODE_OPTIONS}
    - TZ="Asia/Tokyo"
    #Secret Variables
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    user: $CUID:$CGID
    volumes:
    - ./data02:/data
    networks:
      default:
        ipv4_address: $IP_ADDRESS02
    hostname: node-red02

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: $NETWORK

