# -*- coding: utf-8 -*-
# Created by Takuya Ono
# see: https://hub.docker.com/r/nodered/node-red-docker/

version: '3.7'
services:

  node-red:
    #  <node-red-version>-<node-version>-<image-type>
    #image: nodered/node-red:1.3.2-10-minimal
    image: nodered/node-red$VERSION
    restart: always
    environment:
    #- TZ="Asia/Tokyo"
    #- NODE_OPTIONS=--max-old-space-size=2048 --stack-size=984
    - NODE_OPTIONS=${NODE_OPTIONS}
#    - GOOGLE_APPLICATION_CREDENTIALS=/data/adc.json
    #Secret Variablesはgitlab-ciのときだけ
#    - FLOWS=my_flows.json
#    - NODE_OPTIONS=--max_old_space_side=128
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    user: $CUID:$CGID
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./data:/data
#    ports:
#    - "1880:1880"
    networks:
      default:
        ipv4_address: $IP_ADDRESS
    hostname: node-red

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: $NETWORK

